use_frameworks!

target 'XDP_Example' do
  platform :ios, '9.0'
  pod 'XDP', :path => '../'

  target 'XDP_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
